### ISSUE TITLE
Problema con biblatex e lingua italiana

### ISSUE THREAD

**Issue by Zawarud** [poros/LaTeXi#13]
Sto usando Overleaf. Mi da 6 errori, 2 riguardanti biblatex, 6
1)
`>Package caption Warning: Unsupported document class  /usr/local/texlive/2018/texmf-dist/tex/latex/caption/caption.sty (or package) detected, usage of the caption package is not recommended. See the caption package documentation for explanation.`
2)
`Package biblatex Warning: Using fall-back BibTeX(8) /usr/local/texlive/2018/texmf-dist/tex/latex/biblatex/blx-bibtex.def backend: functionality may be reduced/unavailable.`
3) 
`Package blindtext Warning: italian not defined, using English instead. on input line 18.`
La linea 18 e limitrofe sono : 
```
\Blindtext

\begin{figure}
```
Nel file tesi.tex ci sono i pacchetti inerenti, non so perchè dia problemi e non li veda. Esempio : 
```
\usepackage[utf8]{inputenc} %utf8
\usepackage[italian]{babel}
\usepackage[T1]{fontenc}
\usepackage{blindtext}
......
\usepackage[backend=bibtex,bibencoding=ascii]{biblatex}
```
Come posso risolvere questi problemi?

**Comment by poros** [comment]
Credo di avere una build in overleaf per la versione inglese. Provo a farla
per quella italiana nelle vacanze di Natale e ti faccio sapere :)

**Comment by Zawarud** [comment]
Grazie. Perchè o la tesi a fine febbraio e volevo strutturarla durante le vancanze.

**Comment by poros** [comment]
Per `blindtext` ed i warning sull'italiano, non ti preoccupare. Quel pacchetto crea un lorem ipsum per far vedere come viene formattato il documento. Quando vuoi scrivere la tua tesi, puoi togliere blindtext completamente. Aggiungo un commento per farlo più esplicito.

**Comment by poros** [comment]
Ho aggiornato TopTesi e migliorato il supporto per Overleaf copiandolo dal template dell'autore di TopTesi Il warning su caption è scomparso. La cartella è cambiata parecchio, quindi ti conviene ricaricare i file.

Non ho ancora avuto il tempo di guardare nel warning di biblatex

**Comment by poros** [comment]
Ho cambiato il backend da bibtex a biber (sembra essere un backend più moderno) e anche messo `\Blindtext` dentro un ambiente per lingua straniera inglese in modo da evitare i warning.

Ho sottomesso ad Overleaf due template (italiano ed inglese). Se verranno accettati, li metterò in documentazione, ma sei libero di iniziare! :)

**Comment by Zawarud** [comment]
ora provo, eventualmente ti faccio sapere

**Comment by poros** [comment]
Mi raccomando, ricordati di partire dalla versione più recente possibile.

**Comment by poros** [comment]
Ecco il template overleaf: https://www.overleaf.com/latex/templates/latexi-template-italiano/pshzfkvjpfgr
