### ISSUE TITLE
Problema Elenco dei listati.

### ISSUE THREAD

**Issue by Zawarud** [poros/LaTeXi#14]
Non sto riuscendo a far apparire l'elenco dei listati nell'indice, appaiono l'elenco delle figure e delle tabelle ma non dei listati.
Ho provato tutti i comandi possibili( non ricevendo stranamente nessuno errore) anche contemporaneamente:
`\listofcodes` 
`\listoflistings`
`\lstlistoflistings`
Poi C'è la sezione che introduce la numerazione romana per le prime pagine(%DEFINIZIONE SEZIONI IN NUMERAZIONE ROMANA), mala numerazione è sempre quella normale.
Come risolvo il problema?

**Comment by poros** [comment]
Ah cavolo, queste sono le due feature più rognose del template; potrei averle rotte quando ho fatto l'aggiornamento di Toptesi. Quando ho un momento vedo di capire cosa è successo.

**Comment by poros** [comment]
I listati funziona nell mia build (puoi anche vedere il risultato su overleaf https://www.overleaf.com/latex/templates/latexi-english-template/brsprfygydpv).
È già incluso nel template, ma in ogni caso il comando da usare è `\listofcodes`.

**Comment by poros** [comment]
Ho ri-attivato la numerazione romana e sistemato un paio di problemi con l'elenco dei listati come la mancata aggiunta nell'indice (perdonami, non avevo letto bene cosa avessi scritto) e la mancata traduzione italiana.
Ho già aggiornato il template qui su GitHub, mentre quelli su Overleaf sono in fase di approvazione; molto probabilmente verranno aggiornati domani o dopodomani.

Grazie per aver segnalato il problema! :)
