### ISSUE TITLE
Bibliografia che scompare ripetutamente

### ISSUE THREAD

**Issue by AndreaLombax** [poros/LaTeXi#17]
Mi è impossibile modificare la bibliografia che altrimenti scompare dal progetto. (Sto usando overleaf)
Non appena inserisco un altro articolo con @article, una volta effettuato il salvataggio il tutto scompare dal progetto, come se non ci fosse più un file bibliography.bib.

Come mai? È snervante ed ho necessariamente bisogno della bibliografia per effettuare i \ref ...

Grazie mille.

**Comment by poros** [comment]
Ciao, ho compilato entrambi i template su overleaf con un nuova entry `@article` e non riesco a riprodurre il problema della bibliografia che scompare.

Puoi mostrarmi il codice per l'articolo che stai provando ad inserire ed i log di overleaf dopo la compilazione? Se c'è un problema, è probabile che ci sia almeno un warning correlato.

**Comment by AndreaLombax** [comment]
La compilazione va termine senza warning. Mi sono appena accorto, però, che questo problema accade quando all'articolo non do un "doi" oppure un "volume", lasciando quei campi vuoti oppure non menzionandoli...
Alla fine ho optato per un file .tex dove utilizza \bibitem.

**Comment by AndreaLombax** [comment]
So che non è il posto adatto per chiederlo, ma mi sembrava superfluo aprire un'altra Issue...
È possibile modificare il font size? Se sì, come? 

Grazie ancora per avermi risposto
