### ISSUE TITLE
Modifica del logo e relatore nel frontespizio

### ISSUE THREAD

**Issue by chrisoraruf** [poros/LaTeXi#20]
Premetto che potrebbe essere molto facile, ma sono ancora alle basi con LATEX. 

Per come ho strutturato il frontespizio, la grandezza di default del logo risulta veramente troppo piccola. Come posso fare per ingrandirla?

Inoltre, sotto il nome del relatore dovrei inserire il suo dipartimento di appartenenza, ma nella funzione relatore se scrivo relatore{mario\\\dipartimento}, in compilazione esce un errore. Nel candidato{} invece riesco ad andare a capo e scrivere il numero di matricola, ad esempio

**Comment by poros** [comment]
LaTeXi si affida completamente al pacchetto frontespizio per l'impaginazione del frontespizio, usando i default che codificati dal pacchetto toptesi. Ti consiglio di leggere la documentazione di frontespizio (è in italiano) per vedere se ci sono opzioni che possono aiutarti ad ottenere l'impaginazioni che desideri. La trovi qui: https://ctan.org/pkg/frontespizio?lang=en

Nel caso non riuscissi, prova a contattare l'autore del pacchetto. C'è un tasto sempre sulla stessa pagina.

Questi piccoli aggiustamenti possono risultare alquanto frustranti in LaTeX dato che l'impaginazione è frutto della compilazione di un insieme di comandi (WYSIWYM) invece di uno strumento come Word dove quello che vedi è quello che ottieni (WYSIWYG). Ti consiglio quindi di considerare dei compromessi nel caso scoprissi che i cambi che vuoi fare richiedessero una conoscenza di LaTeX molto avanzata. Buona fortuna!
