### ISSUE TITLE
Possibilità di aggiungere Relatrice oltre che Relatore

### ISSUE THREAD

**Issue by ghost** [poros/LaTeXi#21]
Ciao
Innanzitutto vorrei congratularmi per il lavoro questo template sta salvando la mia ragazza da ore di frustrazione che solo word può causare. Purtroppo io non mastico molto bene Latex quindi mi chiedevo se fosse possibile aggiungere nel frontespizio la dicitura Relatrice invece che Relatore. Considerato che la professoressa ci tiene a queste cose non è il caso di farla arrabbiare!
Grazie ancoraa

**Comment by poros** [comment]
Ciao! Il template si basa sul pacchetto TopTesi per le diciture sul frontespizio. Dalla [documentazione](https://ctan.math.washington.edu/tex-archive/macros/latex/contrib/toptesi/toptesi.pdf), dovresti riuscirci usando `\AdvisorName{supervisors’ formal title}`.
Spero che ti possa essere d'aiuto. Se non funziona, prova a chiedere direttamente ai maintainer del pacchetto.
