### ISSUE TITLE
Modifica prima pagina 

### ISSUE THREAD

**Issue by Tommymix** [poros/LaTeXi#22]
Ciao, ho usato e consigliato questo layout perchè è davvero comodo e completo, ma non capisco bene come modificare la prima pagina della tesi. Vorrei cambiare il layout mettendo il logo in alto a sinistra come richiesto dalla mia università. Ho letto qualcosa sulle guide che avete messo a disposizione ma, non essendo esperto, non saprei come procedere (dalle diverse informazioni che ho trovato, ho capito che il layout varia anche in base al tipo di tesi che si sta facendo -triennale, magistrale, dottorato etc.- ma non capisco dove modificare questa variabile)
Avete qualche soluzione?
Grazie!

**Comment by riccardilorenzo** [comment]
Come hai risolto?
