### ISSUE TITLE
Link ai Riferimenti Bibliografici errato

### ISSUE THREAD

**Issue by mistrello96** [poros/LaTeXi#7]
Nell'indice, se si clicca sulla dicitura Riferimenti Bibliografici si viene portati all'ultima pagina dell'ultimo capitolo. Bisognerebbe invece essere portati alla prima pagina di Bibliografia

**Comment by poros** [comment]
Vero, grazie della segnalazione. Ho provato a risolverlo velocemente, ma non ci sono riuscito. Quando ho un po' di tempo libero ci dò un'occhiata.
