### ISSUE TITLE
openright non funziona

### ISSUE THREAD

**Issue by imcatta** [poros/LaTeXi#9]
Voglio far si che i nuovi capitoli inizino sempre sulla pagina di destra quando stampo. Es.
![openright1](https://user-images.githubusercontent.com/38829883/47884901-e8c8b980-de32-11e8-8fb3-daacf6dfd4e9.png)

Credo che dovrebbe bastare mettere `openright` a \documentclass, ma non ho avuto successo

`\documentclass[12pt,openright]{toptesi}`

**Comment by poros** [comment]
Credo che sia un problema di toptesi. Hai gia' provato con `twoside`?

**Comment by imcatta** [comment]
Con `twoside` ho risolto, grazie!
